### ISSUE TITLE
Component: Editor - Upgrade Quill to 2.0

### ISSUE THREAD

**Issue by luin** [primefaces/primeng#14721]
### Describe the bug

Hi 👋
I'm the maintainer of Quill and we are currently working actively for Quill 2.0. Given PrimeNG is still using Quill 1.3, I'm wondering if you'd like to take a PR of upgrading Quill to 2.0? If that's the case, I'd happy to create a PR.

Looking at the code, I think we can make the component support ^1.3 and ^2.0 at the same time so that PrimeNG can release it without a major version bump. There are some option changes introduced in 2.0 so we will also need to update the API documentation accordingly.

### Environment

Quill 2.0

### Angular version

Not applied

### PrimeNG version

17.5.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

Not applied

**Comment by psarno** [comment]
Is there any timeframe for the update to Quill 2.0 for `<p-editor>`?

It would help clear up the console warnings.   It's not causing any actual runtime issues at the moment, but it would be nice to get ahead of it.

> [Violation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.

![image](https://github.com/primefaces/primeng/assets/18640860/8527b226-3638-40e8-b8a9-34ad1f511eac)

**Comment by dgarciarubio** [comment]
Apparently they're deprecating mutation events [this July](https://developer.chrome.com/blog/mutation-events-deprecation).

Is Quill 2.0 in the roadmap? Or any workaround?

**Comment by ThoSap** [comment]
As you can see Quill is again under active development since September 2023.
The new v2.0 version, which will be released soon no longer has the mutation events which will be removed from Chrome/Chromium on July 2024 (Chromium 127).
https://github.com/quilljs/quill/issues/3806#issuecomment-1933250524
https://github.com/quilljs/quill/releases

I do not think the community will switch to TinyMCE, because for open-source it is limited to 1,000 editor loads per month and the CKEditor has many features behind a paywall, for example paste from Microsoft Word, which works in Quill v2.0.

**Comment by pacozevallos** [comment]
Hello, I was testing quill@2.0.0-rc.5 with PrimeNg 17.13 in Angular 17, I am using a reactive form and it does not recognize the default value of a "formControlName". I tried downgrading the version to quill@1.3.7 and it works but I get the "DOMNodeInserted" warning

Any help is welcome.

**Comment by ThoSap** [comment]
In the transitioning phase until the PrimeNG Editor supports Quill v2.0.0 I'm using ngx-quill with the following styles.scss override, so the editor looks the same.

```scss
// Copied from PrimeNG _editor.scss and modified for ngx-quill
quill-editor {
  .ql-toolbar {
    background: $editorToolbarBg;
    border-top-right-radius: $borderRadius;
    border-top-left-radius: $borderRadius;

    &.ql-snow {
      border: $editorToolbarBorder;

      .ql-stroke {
        stroke: $editorToolbarIconColor;
      }

      .ql-fill {
        fill: $editorToolbarIconColor;
      }

      .ql-picker {
        // Custom Quill overrides start
        &:not(.ql-color-picker) {
          width: unset;
        }
        // Custom Quill overrides end

        .ql-picker-label {
          // Custom Quill overrides start
          display: flex;
          align-items: center;
          justify-content: space-between;
          // Custom Quill overrides end
          border: 0 none;
          color: $editorToolbarIconColor;

          // Custom Quill overrides start
          svg {
            position: relative;
            margin-top: unset;
            top: unset;
            right: unset;
          }
          // Custom Quill overrides end

          &:hover {
            color: $editorToolbarIconHoverColor;

            .ql-stroke {
              stroke: $editorToolbarIconHoverColor;
            }

            .ql-fill {
              fill: $editorToolbarIconHoverColor;
            }
          }
        }

        &.ql-expanded {
          .ql-picker-label {
            color: $editorToolbarIconHoverColor;

            .ql-stroke {
              stroke: $editorToolbarIconHoverColor;
            }

            .ql-fill {
              fill: $editorToolbarIconHoverColor;
            }
          }

          .ql-picker-options {
            background: $inputOverlayBg;
            border:$inputOverlayBorder;
            box-shadow:$inputOverlayShadow;
            border-radius: $borderRadius;
            padding: $inputListPadding;

            .ql-picker-item {
              color: $inputListItemTextColor;

              &:hover {
                color: $inputListItemTextHoverColor;
                background: $inputListItemHoverBg;
              }
            }
          }

          &:not(.ql-icon-picker) {
            .ql-picker-item {
              padding: $inputListItemPadding;
            }
          }
        }
      }
    }
  }

  .ql-container {
    border-bottom-right-radius: $borderRadius;
    border-bottom-left-radius: $borderRadius;

    &.ql-snow {
      border: $editorContentBorder;
    }

    .ql-editor {
      background: $inputBg;
      color: $inputTextColor;
      border-bottom-right-radius: $borderRadius;
      border-bottom-left-radius: $borderRadius;
    }
  }

  .ql-snow.ql-toolbar button:hover,
  .ql-snow.ql-toolbar button:focus {
    color: $editorToolbarIconHoverColor;

    .ql-stroke {
      stroke: $editorToolbarIconHoverColor;
    }

    .ql-fill {
      fill: $editorToolbarIconHoverColor;
    }
  }

  .ql-snow.ql-toolbar button.ql-active,
  .ql-snow.ql-toolbar .ql-picker-label.ql-active,
  .ql-snow.ql-toolbar .ql-picker-item.ql-selected {
    color: $editorIconActiveColor;

    .ql-stroke {
      stroke: $editorIconActiveColor;
    }

    .ql-fill {
      fill: $editorIconActiveColor;
    }

    .ql-picker-label {
      color: $editorIconActiveColor;
    }
  }
}

// For ngx-quill component quill-view-html
quill-view-html {
  .ql-container {
    .ql-editor {
      color: $inputTextColor;
    }
  }
}
```

Provider for Angular Standalone:
```ts
provideQuillConfig({
      modules: {
        // This enables syntax highlighting using highlight.js which then also requires us to install this dependency
        syntax: false,
        toolbar: [
          [
            {'font': []},
            {'header': 1},
            {'header': 2},
            {'size': ['small', false, 'large', 'huge']},
            'clean',
          ],
          [
            'bold',
            'italic',
            'underline',
            'strike',
            'code',
            {'script': 'sub'},
            {'script': 'super'},
          ],
          [
            {'color': []},
            {'background': []},
          ],
          [
            'blockquote',
            {'align': []},
            {'list': 'ordered'},
            {'list': 'bullet'},
            {'indent': '-1'},
            {'indent': '+1'},
          ],
          [
            'link',
            'image',
            'code-block',
          ],
        ],
      },
    }),
```

**Comment by aheritier** [comment]
quill 2.0 is out and reported as a security issue (disputed but still concerning): 
[CVE-2021-3163](https://nvd.nist.gov/vuln/detail/CVE-2021-3163) / [GHSA-4943-9vgg-gr5r](https://github.com/advisories/GHSA-4943-9vgg-gr5r)

@luin reported the upgrade almost 3 months ago and also proposed to help to build a PR.

If we had the fact that quill 1.3 won't work in Chrome this summer after deprecating mutation events [this July](https://developer.chrome.com/blog/mutation-events-deprecation) could it be possible for the community to look at this issue and collaborate with @luin to build a fix ?

Thanks a lot

Note: All users upgrading Quill to v2 will have now their editors broken. 

FYI @stephanj

**Comment by luin** [comment]
Looks like only the `scrollingContainer` option is affected: in v2, Quill auto detects the scrolling container, so the option would be ignored. We can add a notice in the documentation about the option is only needed for v1.

> I am using a reactive form and it does not recognize the default value of a "formControlName"

Not familiar with Angular, looking at the code and don't see any usages that could break in v2. Not sure what caused it.

**Comment by aheritier** [comment]
I didn't dig a lot. 
Doing only the upgrade makes the editor empty (no visible error in the console, neither in the build). 
It's loaded but data are not injected.

<img width="1442" alt="Screenshot 2024-04-22 at 07 41 32" src="https://github.com/primefaces/primeng/assets/174600/7727fd0f-eb1e-40c1-8f41-28c881cbc598">

**Comment by luin** [comment]
@aheritier Good catch! Actually 2.0 changed the signature of `clipboard.convert()` that it now accepts an object with two fields `html`/`text`. Also, for getting the html content, it's recommended to use `getSemanticHTML()` since `innerHTML` may contain elements that are only needed for editing (e.g. toolbars).

Here's the changes that make the demo work for me:

```diff
diff --git a/src/app/components/editor/editor.ts b/src/app/components/editor/editor.ts
index 9e578437f..ab7c767ad 100755
--- a/src/app/components/editor/editor.ts
+++ b/src/app/components/editor/editor.ts
@@ -223,7 +223,7 @@ export class Editor implements AfterContentInit, ControlValueAccessor {
         if (this.quill) {
             if (value) {
                 const command = (): void => {
-                    this.quill.setContents(this.quill.clipboard.convert(this.value));
+                    this.quill.setContents(this.quill.clipboard.convert({ html: this.value }));
                 };
 
                 if (this.isAttachedQuillEditorToDOM) {
@@ -296,12 +296,12 @@ export class Editor implements AfterContentInit, ControlValueAccessor {
         });
 
         if (this.value) {
-            this.quill.setContents(this.quill.clipboard.convert(this.value));
+            this.quill.setContents(this.quill.clipboard.convert({ html: this.value }));
         }
 
         this.quill.on('text-change', (delta: any, oldContents: any, source: any) => {
             if (source === 'user') {
-                let html = DomHandler.findSingle(editorElement, '.ql-editor').innerHTML;
+                let html = this.quill.getSemanticHTML();
                 let text = this.quill.getText().trim();
                 if (html === '<p><br></p>') {
                     html = null;
```

**Comment by ThoSap** [comment]
https://slab.com/blog/announcing-quill-2-0/
https://quilljs.com/docs/upgrading-to-2-0/
https://quilljs.com/

**Comment by luin** [comment]
Note that we could make the change backward compatible by checking `Quill.version` and only make [the changes](https://github.com/primefaces/primeng/issues/14721#issuecomment-2068582938) when `Quill.version` is present and it doesn't start with `1.`

**Comment by jcoppieters** [comment]
We're part of Visma and our source code is automatically scanned by Aikido... 
quill is used in prime-ng's p-editor... which we use in our main application.

Aikido reports quill as a security risk and advises to upgrade 1.3.7 => 2.0.0... 
We did, it looked OK, but on save of our document the content isn't saved.

So now we either face security-point penalties or switching to a different editor...

**Comment by jcoppieters** [comment]
Any idea when (or if) the upgrade to quill 2.0 is planned?

**Comment by ThoSap** [comment]
I previously used the following workaround with PrimeNG `17.12.0` and Quill `2.0.0`.
```html
<p-editor (onTextChange)="textChange()" [(ngModel)]="content" [style]="{height: '400px'}"/>
```

```ts
content?: {
    html: string | undefined,
    text: string | undefined,
};

// In any method or service
this.content= { html: c.content, text: undefined });

// When editing/"saving"
textChange(): void {
  if (!this.content) {
    // Your logic here
  }

  // Workaround for Quill v2.0.X until PrimeNG supports it officially
  const htmlContent = this.content as unknown as string;
}
````

**Comment by evertonrivas** [comment]
> I didn't dig a lot. Doing only the upgrade makes the editor empty (no visible error in the console, neither in the build). It's loaded but data are not injected.
> 
> <img alt="Screenshot 2024-04-22 at 07 41 32" width="1442" src="https://private-user-images.githubusercontent.com/174600/324341128-7727fd0f-eb1e-40c1-8f41-28c881cbc598.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MzIyMzEsIm5iZiI6MTcxNDgzMTkzMSwicGF0aCI6Ii8xNzQ2MDAvMzI0MzQxMTI4LTc3MjdmZDBmLWViMWUtNDBjMS04ZjQxLTI4Yzg4MWNiYzU5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQxNDEyMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzEyMzkxYzA1OGIzYmY1Y2ZhNDgzNDA5Mjc4MjdhN2U4NmRhMDFjZWIxZjExNjliMzRkYjY4MTZiMTUxZGQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5IvRaJ59sftyL1oO5wcj4B7VbYkMQZ6tet9spNZ4Ol4">

I have the same problem! How can I solve it?

**Comment by roliveiradvt** [comment]
After upgrading to PrimeNG 17.13.0 the quill component is still broken for me:
![image](https://github.com/primefaces/primeng/assets/168739145/a023e84f-d196-48b5-8af6-8c7e9274569e)

I already tried to update quill to 2.0.1 but didn't do anything.

**Comment by Rodesc** [comment]
> After upgrading to PrimeNG 17.13.0 the quill component is still broken for me: ![image](https://private-user-images.githubusercontent.com/168739145/328221065-a023e84f-d196-48b5-8af6-8c7e9274569e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMDk2MTIsIm5iZiI6MTcxNTAwOTMxMiwicGF0aCI6Ii8xNjg3MzkxNDUvMzI4MjIxMDY1LWEwMjNlODRmLWQxOTYtNDhiNS04YWY2LThjN2U5Mjc0NTY5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQxNTI4MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OTNkNGIwN2EwZDQ2ZTQwOTU5ZDJjN2NjYWExZmJmYjU2NjIyOTc1MGIxMzRlNzM5Mjk0Mzk1ZTdkNGU5ZGRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cm951-TchLMlfv1nrG3rOTXDylxBGKp5jnx4tI0U4gA)
> 
> I already tried to update quill to 2.0.1 but didn't do anything. To be more specific, this issue only happens when you try to use the Editor inside a dialog

Looks like you didn't load the css files correctly. See the bottom of this page: https://www.primefaces.org/primeng-v14-lts/editor

**Comment by vigouredelaruse** [comment]
i'm working on an angular library dependent on primeng ^17.x.x  unfortunately blocked due to  
* optimization bailouts due to quill 1.3.7 dependency 
* extra ##.js files alongside scripts.js that need to be loaded when affected modules are initialized

as per
* transitive dependency on quill 1.3.7 after npm i primeng  
* https://github.com/primefaces/primeng/blob/master/package.json:devDependencies:quill

the error
``` node_modules\primeng\fesm2022\primeng-editor.mjs depends on 'quill'. CommonJS or AMD dependencies can cause optimization bailouts. For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies```

the error artifact (partial scripts.js minification) is generated whether or not primeng::EditorModule is imported
![image](https://github.com/primefaces/primeng/assets/31052867/8da78d5b-3e02-4315-a692-6fe83387b849)

looking forward to the successful pr validation

**Comment by EdManukyan** [comment]
@luin I have a question.
so in the old version and even in rc2 `valueGetter: (quillEditor: QuillType, editorElement: HTMLElement) => string | any; `method looked like this, but in the newer version and in the latest one quill has this change `valueGetter: import("@angular/core").InputSignal<(quillEditor: QuillType) => string | any>;` which is great that quill uses signals. In my code the usage is like this.
```
  editor: Quill;
  const editorValue = this.quillEditorComponent.valueGetter();

    let noChanges = editorValue(this.editor) === this.formControl.value;
    if (noChanges) return;

    // use case falsy values (example, new/temp entity)
    noChanges = !editorValue(this.editor) && !this.formControl.value;
```
which seems to be solution for my problem , but the test fails 
test:
```
    beforeEach(() => {
      component.formControl = new UntypedFormControl('', { updateOn });
      markAsDirtySpy = spyOn(component.formControl, 'markAsDirty');
      setValueSpy = spyOn(component.formControl, 'setValue');
      qecValidateSpy = spyOn(component.quillEditorComponent, 'validate').and.returnValue(null);
      qecValueGetterSpy = spyOn(component.quillEditorComponent, 'valueGetter');
    });

    it('should update value', () => {
      component.ngOnDestroy();
      expect(markAsDirtySpy).toHaveBeenCalled();
      expect(setValueSpy).toHaveBeenCalledWith(expectedUpdateValue);
    });

```

error:
TypeError: editorValue is not a function
i was not able to find proper way of valueGetter() for version 2.0

**Comment by luin** [comment]
@EdManukyan I don't think the code belongs to Quill so I may not be the best person for this question

**Comment by EdManukyan** [comment]
@luin my apologies this should been asked for the ngx-quill, and thanks for the quick response and beautiful upgrade of the Quill

**Comment by chriskyndrid** [comment]
I migrated to 2 and it worked fine with the latest 2.0.1 and primeng release. However, regards the reactive form issue, you could do something like this:

```typescript
public modelValue: any;

this.systemFormControl.valueChanges.subscribe(
    val => {
        if (val == null || this.modelValue != val) {
            if (this.format.toLowerCase() == 'json' && this.systemService.isObject(val)) {
                this.modelValue = JSON.stringify(val);
            } else {
                this.modelValue = val;
            }
        }
    }
),

modelChange(newValue: any): void {
    this.modelValue = newValue;
    if (this.format.toLowerCase() == 'json') {
        this.systemFormControl.setValue(JSON.parse(newValue));
    } else {
        this.systemFormControl.setValue(newValue);
    }
}
```

template:

```html
<span>
    <p-editor
            [(ngModel)]="modelValue"
            [style]="cssStyle"
            (ngModelChange)="modelChange($event)"
            [placeholder]="placeholder"
    >
    </p-editor>
</span>

```

you can then bind a FormControl as an AbstractControl in your own component wrapper and have bind to [(ngModel]).

**Comment by MartinaAnt** [comment]
Hi @luin, any idea when (or if) the fix for v. 2.0 is planned?

**Comment by luin** [comment]
I'm not the maintainer of this repo but [the patch I proposed](https://github.com/primefaces/primeng/issues/14721#issuecomment-2068582938) should make this library work with Quill 2.0

**Comment by cetincakiroglu** [comment]
Hi @luin,

Thanks for the support! We've added it into 18.0.0-rc.1

**Comment by ThoSap** [comment]
@cetincakiroglu can you please include the pull request #15764 already with the PrimeNG 17.18.2 release?

I don't think anything speaks against it as this PR both supports Quill 1.X.X and 2.X.X, then we could use Angular 17 + PrimeNG 17.18.2 and Quill after the 25th of July 2024.

**Comment by tuankhoiutc260** [comment]
> I previously used the following workaround with PrimeNG `17.12.0` and Quill `2.0.0`.
> 
> ```
> <p-editor (onTextChange)="textChange()" [(ngModel)]="content" [style]="{height: '400px'}"/>
> ```
> 
> ```ts
> content?: {
>     html: string | undefined,
>     text: string | undefined,
> };
> 
> // In any method or service
> this.content = { html: c.content, text: undefined });
> 
> // When editing/"saving"
> // You do not necessarily need this callback in the `<p-editor/>`, the content variable will always have the last value due to the Angular model/two-way binding
> textChange(): void {
>   if (!this.content) {
>     // Your logic here
>   }
> 
>   // Workaround for Quill v2.0.X until PrimeNG supports it officially
>   const htmlContent = this.content as unknown as string;
> }
> ```

I'm a newbie in Angular, it works for me. Thanks very much!

**Comment by ThoSap** [comment]
🥳🥳🥳
https://github.com/primefaces/primeng/releases/tag/17.18.3

Thanks @fabiancabau @luin @cetincakiroglu

**Comment by rishabh010189** [comment]
> > > After upgrading to PrimeNG 17.13.0 the quill component is still broken for me: ![image](https://private-user-images.githubusercontent.com/168739145/328221065-a023e84f-d196-48b5-8af6-8c7e9274569e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMDk2MTIsIm5iZiI6MTcxNTAwOTMxMiwicGF0aCI6Ii8xNjg3MzkxNDUvMzI4MjIxMDY1LWEwMjNlODRmLWQxOTYtNDhiNS04YWY2LThjN2U5Mjc0NTY5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQxNTI4MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OTNkNGIwN2EwZDQ2ZTQwOTU5ZDJjN2NjYWExZmJmYjU2NjIyOTc1MGIxMzRlNzM5Mjk0Mzk1ZTdkNGU5ZGRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cm951-TchLMlfv1nrG3rOTXDylxBGKp5jnx4tI0U4gA)
> > > I already tried to update quill to 2.0.1 but didn't do anything. To be more specific, this issue only happens when you try to use the Editor inside a dialog
> > 
> > 
> > Looks like you didn't load the css files correctly. See the bottom of this page: https://www.primefaces.org/primeng-v14-lts/editor
> 
> ![image](https://private-user-images.githubusercontent.com/168739145/328233998-233ab794-ebb6-4bb5-82d5-256047407b38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMDY1ODQsIm5iZiI6MTczMzIwNjI4NCwicGF0aCI6Ii8xNjg3MzkxNDUvMzI4MjMzOTk4LTIzM2FiNzk0LWViYjYtNGJiNS04MmQ1LTI1NjA0NzQwN2IzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwNjExMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjBlZWJiMWJmMDBmYWIxMjBjZDM5M2UyY2IxMWU3MTIxZDgyMTE5OWNhNjZmNmY0N2FiMTI1NDQ2NmZkYzI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.V-WhSMgqDWgfEz9o2t6bR2SYG1rsPWtDMtDT7VER2YE)
> 
> They are there, the editor doesn't work ONLY IF it is inside the dialog. I have another instance of the editor working in my application, just the one inside the dialog doesn't work (tried adding to other dialogs just to make sure that was the issue)

I am facing the same issue for child routing standalone components.
Did you happen to find any fix?
