### ISSUE TITLE
ERROR TypeError: this.rootEl?.setAttribute is not a function after migration to v19

### ISSUE THREAD

**Issue by eciuca** [primefaces/primeng#17419]
### Describe the bug

user-list.component.html:79 ERROR TypeError: this.rootEl?.setAttribute is not a function
    at Tooltip.ngAfterViewInit (primeng-basecomponent.mjs:58:26)
    at Tooltip.ngAfterViewInit (primeng-tooltip.mjs:267:15)
    at callHookInternal (core.mjs:4277:14)
    at callHook (core.mjs:4304:13)
    at callHooks (core.mjs:4258:17)
    at executeInitAndCheckHooks (core.mjs:4208:9)
    at refreshView (core.mjs:14964:21)
    at detectChangesInView (core.mjs:15105:9)
    at detectChangesInViewIfAttached (core.mjs:15065:5)
    at detectChangesInEmbeddedViews (core.mjs:15024:13)

This is line 79:
`<app-warehouse ngDefaultControl [ngModel]="(user.warehouse$ | async) || undefined" />`

and ngModel is defined like this
`ngModel = model<Warehouse>();`

### Reason for not contributing a PR

- [x] Lack of time
- [x] Unsure how to implement the fix/feature
- [ ] Difficulty understanding the codebase
- [ ] Other

### Reproducer

https://stackblitz.com/edit/github-ezuftcgh-xq53ixgg?file=src%2Fapp%2Fwarehouse.component.html

### Environment

Chrome browser

### Angular version

19.1.0

### PrimeNG version

v19

### Node version

22.11.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

Just go to a page displaying the component

### Expected behavior

This error should not be thrown.

This is the failing code:

```
ngAfterViewInit() {
        this.rootEl = this.el?.nativeElement;
        if (this.rootEl) {
            this.rootEl?.setAttribute(this.attrSelector, ''); // maybe an additional check is needed here to see if the element has the setAttribute method ?
        }
    }
```

**Comment by sameerthekhans** [comment]
This isn't a bug. In your StackBlitz example, you've added `pTooltip` to an `<ng-container>`, which doesn't render as a real DOM element in the browser. Since tooltips need to attach to an actual HTML element, they won't work with `<ng-container>`. If you change the `<ng-container>` to a `<div>` or any other valid HTML element, you'll see the tooltip works as expected.

Read more about `ng-container` [here](https://angular.dev/api/core/ng-container#description)

FYI @cagataycivici

**Comment by eciuca** [comment]
oh, noted. Thanks a lot for your answer !
