### ISSUE TITLE
ERROR TypeError: this.document.head.prepend is not a function in 18.0.0-rc.1

### ISSUE THREAD

**Issue by junan-trustarc** [primefaces/primeng#16875]
### Describe the bug

for ng serve, I am getting below error after upgraded to 18.0.0-rc.1

one thing this project is using angular SSR.

```
ERROR TypeError: this.document.head.prepend is not a function
    at _UseStyle.use (C:\TrustArc\arc-ui\.angular\cache\18.2.12\arc-ui\vite\deps_ssr\chunk-7G5ZQONS.js:846:34)
    at _BaseStyle.load (C:\TrustArc\arc-ui\.angular\cache\18.2.12\arc-ui\vite\deps_ssr\chunk-7G5ZQONS.js:1093:42)
    at _Toast._loadThemeStyles (C:\TrustArc\arc-ui\.angular\cache\18.2.12\arc-ui\vite\deps_ssr\chunk-F55NIZH2.js:187:22)
    at _load (C:\TrustArc\arc-ui\.angular\cache\18.2.12\arc-ui\vite\deps_ssr\chunk-F55NIZH2.js:138:12)
    at eval (C:\TrustArc\arc-ui\.angular\cache\18.2.12\arc-ui\vite\deps_ssr\chunk-F55NIZH2.js:141:37)
    at eval (C:\TrustArc\arc-ui\.angular\cache\18.2.12\arc-ui\vite\deps_ssr\chunk-JVQNSWXU.js:593:11)
    at Array.map (<anonymous>)
    at Object.emit (C:\TrustArc\arc-ui\.angular\cache\18.2.12\arc-ui\vite\deps_ssr\chunk-JVQNSWXU.js:592:26)
    at Object.setTheme (C:\TrustArc\arc-ui\.angular\cache\18.2.12\arc-ui\vite\deps_ssr\chunk-7G5ZQONS.js:670:21)
    at _PrimeNG.onThemeChange (C:\TrustArc\arc-ui\.angular\cache\18.2.12\arc-ui\vite\deps_ssr\chunk-7G5ZQONS.js:1210:20)
```

### Environment

"primeng": "^18.0.0-rc.1",
"@primeng/themes": "^18.0.0-rc.1",

happening in ng serve only.

### Angular version

18.2.x

### PrimeNG version

18.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.15.1

### Browser(s)

chrome 131.0.6778.86 but all browsers are same

**Comment by mertsincan** [comment]
Fixed for the next version. Thank you!

**Comment by junan-trustarc** [comment]
> Fixed for the next version. Thank you!

@mertsincan thanks, do you know when rc.2 will be released?
