### ISSUE TITLE
Dropdown and Multiselect: ERROR TypeError: value.trim is not a function

### ISSUE THREAD

**Issue by aleadkeyhole** [primefaces/primeng#12525]
### Describe the bug

![image](https://user-images.githubusercontent.com/13691337/213480348-17ad69e1-1232-4621-a5e2-213dd11a97ea.png)

Upgraded this morning, upon clicking a dropdown or multiselect specifically this error occurs. Appears that the trim() function is being called upon something else then a string. 

### Environment

irrelevant

### Angular version

15.1.0

### PrimeNG version

15.1.0

### Build / Runtime

TypeScript

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.12.0

**Comment by NahiaLC** [comment]
Same problem here!

Angular v15.1.1
PrimeNG v15.1.0
Node v16.15.1

**Comment by adglow-izemfr** [comment]
same problem here!

Angular v15.1.1
primeng v15.1.0
Node v18.13.0

**Comment by hugograf** [comment]
It is maybe Angular bug, see [ngClass klass property](https://github.com/angular/angular/issues/48779)

**Comment by pkozlowski-opensource** [comment]
> It is maybe Angular bug, see https://github.com/angular/angular/issues/48779

Actually, the issue is that the overlay implementation is supplying an empty object (`{}`) to a binding that accepts strings only. The offending line seems to be https://github.com/primefaces/primeng/blob/master/src/app/components/overlay/overlay.ts#L117

So this is rather a bug that should be fixed on the PrimeNG side.

**Comment by olegkap** [comment]
I am experiencing the same issue after upgrade to 15.1

**Comment by PetrJajtner** [comment]
I think there is a problem with line `_styleClass: string | undefined;` (https://github.com/primefaces/primeng/blob/master/src/app/components/overlay/overlay.ts#L233) and invoking styleClass property. It is evaluated using `ObjectUtils.merge` where both parameters are undefined and therefore result of this method is empty object. 
One possible solution is inserting them into the array and joining by space directly in getter:
```
get styleClass(): string {
  return [this._styleClass ?? '', (this.modal ? this.overlayResponsiveOptions?.styleClass : this.overlayOptions?.styleClass) ?? ''].join(' ').trim();
}
```

**Comment by AlejandroMHOB** [comment]
Same problem here. After update to primeng 15.1 with latest Angular version.

**Comment by cancrexo** [comment]
Same here.
ng 15.05
node 18.12
primeNG 15.1.0

Simple clicking on the dropdown throws error on console

**Comment by Phillip9587** [comment]
Reproduction on Stackblitz: https://stackblitz.com/edit/primeng-dropdown-demo-gbr32c?file=src/app/app.component.html

**Comment by olegkap** [comment]
Looks like the issue with Angular, like someone mentioned, I rolled back Angular to 15.1.0 and kept primeNG at 5.1.0 and all worked, so I think we need to test it once Angular 15.1.2 comes out perhaps.

**Comment by PetrJajtner** [comment]
Nope, Angular 15 only simplified the setter named `klass`. The problem is in PrimeNG (see my comment above) which produced object instead of string. Btw. PrimeNG uses very ugly code with many types of any. I would recommend core team of PrimeNG to use strict type checking.

**Comment by olegkap** [comment]
I figured that what fixed it for me  after I rolled back some changes so I thought it might be Angular 15.1.1.
I do agree some of the code in PrimeNG would be good to refactor when it comes to types.
I guess will wait then for PrimeNG 15.1.1

**Comment by yghandor** [comment]
it works with Version  15.1.0 and latest primeng (15.1.0) 
and this is by just remove the "^"

**Comment by PetrJajtner** [comment]
> it works with Version 15.1.0 and latest primeng (15.1.0) and this is by just remove the "^"

I don't think so, try my project: https://stackblitz.com/edit/pj-angular-ngclass-setting-bug?file=package.json

**Comment by mertsincan** [comment]
Thanks a lot for the report! Fixed now.

**Comment by klanglie** [comment]
I feel that this is not fixed. I am running latest angular, 15.2.8 and the latest PrimeNG, 15.4.1. Before updating, my project worked fine. It seems like it is PrimeNG and NOT Angular that is still the cause for this. I wish I could pinpoint further but have tried to debug and handle the error without any success so far.

**Comment by sbkt007** [comment]
Mine is resolved after updating the angular and primeng same version. I was installed angular 15.0.0 and primeng 15.0.0. Updated both the versio 15.2.1 it got resolved.

**Comment by abiram9291** [comment]
> > It is maybe Angular bug, see [angular/angular#48779](https://github.com/angular/angular/issues/48779)
> 
> Actually, the issue is that the overlay implementation is supplying an empty object (`{}`) to a binding that accepts strings only. The offending line seems to be https://github.com/primefaces/primeng/blob/master/src/app/components/overlay/overlay.ts#L117
> 
> So this is rather a bug that should be fixed on the PrimeNG sid

**Comment by abiram9291** [comment]
has this been fixed at all?
I am still facing this issue. any help is appreaciated.

**Comment by bananalasmari** [comment]
**same issue here any fixes?!**

 "@angular": "^15.0.0",
"primeng": "^15.0.0",
