### ISSUE TITLE
 Initializers are not allowed in ambient contexts v7.0.0-beta.1 - Angular 6

### ISSUE THREAD

**Issue by Pikadili83** [primefaces/primeng#6771]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
After upgrading to 7.0.0-beta.1, I get error message after ng serve:

ERROR in node_modules/primeng/components/picklist/picklist.d.ts(65,28): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/primeng/components/picklist/picklist.d.ts(66,28): error TS1039: Initializers are not allowed in ambient contexts.

Problem is this:
readonly SOURCE_LIST = -1;
readonly TARGET_LIST = 1;

**Expected behavior**
No error

**Minimal reproduction of the problem with instructions**
Upgrade to the version 7.0.0-beta.1.

**Please tell us about your environment:**
Windows

* **Angular version:** 
6.0.3

* **PrimeNG version:** 
7.0.0-beta.1

* **Language:** 
Typescript 2.7.2

**Comment by dduraipandian91** [comment]
I had the same problem with beta version. Then i installed older one.

"primeicons": "^1.0.0",
"primeng": "^6.1.2",

**Comment by ymenager** [comment]
+1

**Comment by Pikadili83** [comment]
I don't think that reverting to the older version is a solution... The thing is that you need to upgrade your Typescript and Angular to the latest versions and then it works.
I just didn't want to upgrade Angular since some other third party libraries were not supporting latest Angular yet. 
If you don't have these dependencies just update your typescript and angular to the latest and error will disappear.
But again, I think that Primeng should work with older Typescript versions too.

**Comment by ymenager** [comment]
Ah, I see.... then it might be more appropriate to change the issue description to "Doesn't work on 6" and then prime can decide if it's a bug or a limitation

**Comment by cagataycivici** [comment]
PrimeNG 7.x requires Angular 7.
