### ISSUE TITLE
PrimeNG v11.4.4 fails with template type check errors on dropdown component.

### ISSUE THREAD

**Issue by rajeevatprecisely** [primefaces/primeng#10456]
**I'm submitting a bug** 
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
In our application, I have created a wrapper component to wrap the primeng-dropdown component. The similar setup I have created on Stackblithz. Below is the URL. However this is not reproducible there. But in my local setup it throws error while building/serving the app.

https://stackblitz.com/edit/angular-11-new-5jbpwg

**Current behavior**
When **IVY** is disabled and **fullTemplateTypeCheck** is enabled in **tsconfig**, below error is thrown-

> Error: node_modules/primeng/dropdown/primeng-dropdown.d.ts.Dropdown.html(63,43): Property 'emptyFilter' does not exist on type 'Dropdown'.
> node_modules/primeng/dropdown/primeng-dropdown.d.ts.Dropdown.html(69,43): Property 'empty' does not exist on type 'Dropdown'.

**Expected behavior**
It should not throw error as mentioned above.

**Minimal reproduction of the problem with instructions**
Unfortunately, this is not reproducible on StackBlitz - https://stackblitz.com/edit/angular-11-new-5jbpwg (Hello Component Wraps Prime NG's dropdown component) 

**What is the motivation / use case for changing the behavior?**
I am trying to upgrade Angular and PrimeNG version (from 10 to 11) to use new features. Angular upgrade is fine, but after upgrading PrimeNg from v10 to v11, it is giving the above mentioned error. If I turn off the **fullTemplateTypeCheck** then it works fine. But I do not want to turn this templateCheck off.

**Please tell us about your environment:**
Our setup is Hybrid, where we are running Angular JS and Angular 11 both. We use Angular NgUpgrade module to downgrade new components and use it inside old Angular JS. 

Local setup details: O/S - Windows 10; Node Version: 12.14.1
* **Angular version:** 11.2.5

* **PrimeNG version:** 11.4.4
With older PrimeNG version i.e. 10.0.3 it was working.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Build / Serve issue. So doesn't reach out to browser.
 
* **Language:** [TypeScript 4.0.2 | ES6/7]

* **Node (for AoT issues):** `node --version` =   12.14.1

**Comment by yigitfindikli** [comment]
PrimeNG is not compatible with the old angular js.

**Comment by rajeevatprecisely** [comment]
Hi @yigitfindikli,

We are not using PrimeNG in Angular JS. We are using it with new Angular (typescript) only. This was working fine till 10.0.3 version of PrimeNG. But after upgrading it to v11 it started throwing error.

If I disable **fullTemplateTypeCheck** i.e. `"fullTemplateTypeCheck": false` in tsconfig.json then it passes and serves/build the project.
