### ISSUE TITLE
MegaMenuModule component : ERROR TypeError: Cannot read property 'styleClass' of undefined

### ISSUE THREAD

**Issue by brunoksi** [primefaces/primeng#5169]
after update primeNg package 4.1.1 to 5.2.0 the component MegaMenu 

ng:///MegaMenuModule/MegaMenu.ngfactory.js:91 ERROR TypeError: Cannot read property 'styleClass' of undefined
    at Object.eval [as updateDirectives] (ng:///MegaMenuModule/MegaMenu.ngfactory.js:125)
    at Object.debugUpdateDirectives [as updateDirectives] (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14867)
    at checkAndUpdateView (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14014)
    at callViewAction (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14365)
    at execEmbeddedViewsAction (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14323)
    at checkAndUpdateView (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14015)
    at callViewAction (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14365)
    at execEmbeddedViewsAction (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14323)
    at checkAndUpdateView (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14015)
    at callViewAction (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14365)

![image](https://user-images.githubusercontent.com/17805950/36355084-5bc86b9c-14bc-11e8-91d6-d5b1034af0a3.png)

this error does not occur in version 4.1.1

**Comment by ldzhu** [comment]
+1

**Comment by ldzhu** [comment]
primeng/src/app/components/megamenu/megamenu.ts  line 27:

```html
<a *ngIf="category.routerLink" [routerLink]="category.routerLink" [queryParams]="category.queryParams" [routerLinkActive]="'ui-state-active'" [routerLinkActiveOptions]="category.routerLinkActiveOptions||{exact:false}" 
                            [attr.target]="category.target" [attr.title]="category.title" [attr.id]="category.id"
                            (click)="itemClick($event, category)" [ngClass]="{'ui-menuitem-link ui-corner-all':true,'ui-state-disabled':child.disabled}" [ngStyle]="child.style" [class]="child.styleClass">
                            <span class="ui-menuitem-icon fa fa-fw" *ngIf="category.icon" [ngClass]="category.icon"></span>
                            <span class="ui-menuitem-text">{{category.label}}</span>
                        </a>
```

where is the **child** defined ?
