### ISSUE TITLE
Issue #10456 is marked as closed. But fullTemplateTypeCheck for v11.4.4. is still failing.

### ISSUE THREAD

**Issue by rajeevatprecisely** [primefaces/primeng#10467]
**I'm submitting a bug again since I can't re-open #10456** 
```
[x] bug report => https://github.com/primefaces/primeng/issues/10456
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
NA

**Current behavior**
Prior to v11 (i.e. v10.0.3) PrimeNG components/modules were working fine in my Hybrid Environment. The fulltemplateTypeCheck was set to true and everything - serve/build was working fine. After upgrading to v11 we started getting below issue. -

```
Error: node_modules/primeng/dropdown/primeng-dropdown.d.ts.Dropdown.html(63,43): Property 'emptyFilter' does not exist on type 'Dropdown'.
node_modules/primeng/dropdown/primeng-dropdown.d.ts.Dropdown.html(69,43): Property 'empty' does not exist on type 'Dropdown'.
```

**Expected behavior**
While the *fullTemplateTypeCheck* is turned on (set to _true_) we should be able to serve/build the project.

**Minimal reproduction of the problem with instructions**
Not sure on reproducing this. Any guidance/advise here?

**What is the motivation / use case for changing the behavior?**
fullTemplateTypeCheck is essential configuration and we cannot keep it false.

**Please tell us about your environment:**
OS: Win 10. NPM, NG-CLI

About Environment - We have an hybrid environment where Angular v11 and Angular JS co-exists. To give more context AngularJS module is being bootstrapped via Angular 11 only, thus making no impact on New Components and elsewhere. With **PrimeNG version 10 it is still working fine**. Also if I **turn off fullTemplateTypeCheck config, it works fine again.**

* **Angular version:**
v11

* **PrimeNG version:** 5.X
v11.4.4

* **Browser:**
NA since issue occurs while compiling/building the app.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   12.14.1

**Comment by rajeevatprecisely** [comment]
@yigitfindikli @cagataycivici 
Please advise/help.

**Comment by pedro21900** [comment]
não seu tsconfig.js substitua o fullTemplateTypeCheck por :
```json
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
```

Because according to the documentation https://angular.io/guide/template-typecheck ,fullTemplateTypeCheck it was discontinued .

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
