### ISSUE TITLE
Property 'columnheader' does not exist on type 'SortableColumn'.

### ISSUE THREAD

**Issue by huineng** [primefaces/primeng#8693]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
```

in commit https://github.com/primefaces/primeng/commit/77e85944c0e828001b9dd5e586dcae7af60257e2#diff-0d572934b5355d23d4b13eb1f307f180R2530 
you added   '[attr.role]': 'columnheader',

compiling with angular 9.1  i get the error Directive SortableColumn, Property 'columnheader' does not exist on type 'SortableColumn'.

this is true, columnheader is not defined

thanks

**Comment by Srafington** [comment]
Issue looks to have been caused by #8684

**Comment by cagataycivici** [comment]
9.0.4 will be released in an hour.
