### ISSUE TITLE
p-cascadeSelect: `options` input type mismatch with official documentation.

### ISSUE THREAD

**Issue by Gykonik** [primefaces/primeng#13466]
### Describe the bug

The CascadeComponent defines the options input as:

`@Input() options: string[] | string | undefined | null;`
[Source](https://github.com/primefaces/primeng/blob/7ba83aec8acbed8f676f6cd8fb9800f3faa30e89/src/app/components/cascadeselect/cascadeselect.ts#L85)

However, the official [documentation](https://primeng.org/cascadeselect) provides an example where options is expected to be an array of objects:

`<p-cascadeSelect [(ngModel)]="selectedCity" [options]="countries" optionLabel="cname" optionGroupLabel="name" [optionGroupChildren]="['states', 'cities']" [style]="{ minWidth: '14rem' }" placeholder="Select a City"></p-cascadeSelect>
`

With the corresponding data:
```
this.countries = [
  {
    name: 'Australia',
    code: 'AU',
    states: [
      {
        name: 'New South Wales',
        cities: [
          { cname: 'Sydney', code: 'A-SY' },
          { cname: 'Newcastle', code: 'A-NE' },
          { cname: 'Wollongong', code: 'A-WO' }
        ]
      },
      {
        name: 'Queensland',
        cities: [
          { cname: 'Brisbane', code: 'A-BR' },
          { cname: 'Townsville', code: 'A-TO' }
        ]
      }
    ]
  },
  ...
];
```
 

### Environment

Angular 16
PrimeNG 16

### Angular version

16.1.2

### PrimeNG version

16.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Expected behavior

The type definition for the options input should match the official documentation (or the other way around) and support arrays of objects. Or am I missing anything obvious here?

**Comment by Gykonik** [comment]
Furthermore, I think that it needs undefined-checks for `isOptionGroup`:

```
isOptionGroup(option: string | object, level: number) {
  return Object.prototype.hasOwnProperty.call(option, (this.optionGroupChildren as string)[level]);
}
```
[source](https://github.com/primefaces/primeng/blob/7ba83aec8acbed8f676f6cd8fb9800f3faa30e89/src/app/components/cascadeselect/cascadeselect.ts#L648
)

1. I think it should be `as string[]` or even `as any` as it was done in `OptionGroupSub` [reference](https://github.com/primefaces/primeng/blob/7ba83aec8acbed8f676f6cd8fb9800f3faa30e89/src/app/components/cascadeselect/cascadeselect.ts#L185C5-L187C6)
2. This fails when not passing in any option for `optionGroupChildren` or passing a string.

**Comment by jesuscano80** [comment]
Any news about this?

**Comment by pmestrum** [comment]
I am also blocked because of this bug, since I upgraded vrom v15 to latest version.

**Comment by randy9527** [comment]
Source of Cascade Select is always hierarchical objects, `string[] | string | undefined | null` really doesn't make sense.

**Comment by toute-la-journee** [comment]
any updates?

**Comment by ThreatLockerNathanHolden** [comment]
Reporting the same issue after upgrading project from PrimeNG v15.4.1 to v16.9.1.

**Comment by msg-jstren** [comment]
Type issue for the options input still remains on PrimeNG version 17.18.8
Should have an Interface with hierarchical objects!

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation and try the latest PrimeNG version(v19). If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,

**Comment by zachsteffens-wy** [comment]
https://stackblitz.com/edit/kmyxqbbr?file=src%2Fapp%2Fcascade-select-basic-demo.ts

Still an issue. I've made the tsconfig a bit more strict and generated interface types for countries, states and cities. 

This throws a compile error.
```
Error: src/app/cascade-select-basic-demo.html:3:50 - error TS2322: Type 'country[] | undefined' is not assignable to type 'string | string[] | undefined'.
  Type 'country[]' is not assignable to type 'string | string[] | undefined'.
    Type 'country[]' is not assignable to type 'string[]'.
      Type 'country' is not assignable to type 'string'.

3     <p-cascadeselect [(ngModel)]="selectedCity" [options]="countries" optionLabel="cname" optionGroupLabel="name" [optionGroupChildren]="['states', 'cities']" [style]="{ minWidth: '14rem' }" placeholder="Select a City" />
```
