### ISSUE TITLE
Error: Cannot resolve type entity SafeHtmlPipe to symbol

### ISSUE THREAD

**Issue by Valera1980** [primefaces/primeng#13218]
### Describe the bug

after upgrade PrimeNg to 16.0.1 I get error after commang "ng s"

### Environment

angular 16.1.1
primeNg 16.0.1

### Reproducer

https://codesandbox.io/s/dkgsgl?file=/package.json:105-111

### Angular version

16.1.1

### PrimeNG version

16.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v18.16.0

### Browser(s)

Version 114.0.5735.134 (Official Build) (64-bit)

### Steps to reproduce the behavior

1. Install angular ng update @angular/cli @angular/core --force to version 16.1.1
2. Install primeng v 16.0.1
3. run ng s
4. you can see in console:
`✔ Browser application bundle generation complete.

Initial Chunk Files   | Names         |  Raw Size
vendor.js             | vendor        |   1.97 MB | 
scripts.js            | scripts       | 820.51 kB | 
styles.css, styles.js | styles        | 483.89 kB | 
polyfills.js          | polyfills     | 335.60 kB | 
runtime.js            | runtime       |   6.52 kB | 
main.js               | main          |   3.17 kB | 

                      | Initial Total |   3.58 MB

Build at: 2023-06-16T15:33:28.566Z - Hash: caf2cdd4feccb5aa - Time: 5139ms

./src/app/app.module.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Cannot resolve type entity SafeHtmlPipe to symbol

Error: node_modules/primeng/menu/menu.d.ts:139:100 - error TS2304: Cannot find name 'SafeHtmlPipe'.

139     static ɵmod: i0.ɵɵNgModuleDeclaration<MenuModule, [typeof Menu, typeof MenuItemContent, typeof SafeHtmlPipe], [typeof i1.CommonModule, typeof i2.RouterModule, typeof i3.RippleModule, typeof i4.TooltipModule], [typeof Menu, typeof i2.RouterModule, typeof i4.TooltipModule]>;`

### Expected behavior

1. Install angular ng update @angular/cli @angular/core --force to version 16.1.1
2. Install primeng v 16.0.1
3. run ng s
4. no errors in console

**Comment by pratyush22** [comment]
Facing the same issue in my project as well after updating Primeng.

**Comment by HeavyRainLQ** [comment]
Same issue here

**Comment by jhcpeixoto** [comment]
Same issue there

**Comment by ruskovweb** [comment]
Same issue here

**Comment by puntosur-winston** [comment]
same issue

![image](https://github.com/primefaces/primeng/assets/88198193/f2d0e514-c91e-42e5-a09e-60b75f4c0de9)

**Comment by psarno** [comment]
Same, can not compile under either the new esbuild or webpack.

**Comment by dloprodu** [comment]
same issue, please fix it :(

**Comment by borismm3** [comment]
Same issue, need help pls!
![image](https://github.com/primefaces/primeng/assets/88692480/217b29b9-e8dc-4011-b21f-949f6119a4b2)

**Comment by faileon** [comment]
Quick workaround is to downgrade to primeng 16.0.0. [More info](https://github.com/primefaces/primeng/issues/13211#issuecomment-1596985630)
