### ISSUE TITLE
TreeNode: data is no longer generic

### ISSUE THREAD

**Issue by kyjus25** [primefaces/primeng#13183]
### Describe the bug

The data attribute of TreeNode is now type `any`, which breaks the previous implementation of passing in a generic `<T>` value for data.
https://github.com/primefaces/primeng/blob/master/src/app/components/api/treenode.ts

The TreeNode would now probably have to be defined as something like `TreeNode & { data?: T }`, which is not ideal.

![Screenshot from 2023-06-12 12-37-07](https://github.com/primefaces/primeng/assets/6710794/ad014efb-87a0-48b2-be2d-e5658fbd179a)

Here is what it used to be:
https://github.com/primefaces/primeng/blob/14.2.3/src/app/components/api/treenode.ts

### Environment

Angular 16
PrimeNG 16

### Angular version

16.0.0

### PrimeNG version

16.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Expected behavior

TreeNode should accept a generic data type instead of any

**Comment by thetric** [comment]
Broken in commit https://github.com/primefaces/primeng/commit/d3b00fcd6f7cfe30d1261fa893211062d9fa26f6.

I was quite surprised of this breaking change in the public API because virtually no breaking changes was documented

**Comment by olegkap** [comment]
There is similar breaking change in cascade select control where now you can only bind any[] and not specific type as before.
I will work on example case later today but just wanted to give heads up since it might be related

**Comment by bhalperin** [comment]
👏

**Comment by ficifor** [comment]
The data attribute is still type any, the generic <T> value is not being passed on.

**Comment by gerbermichi** [comment]
The bug still exists in versoin 16.0.2.

**Comment by bhalperin** [comment]
> The bug still exists in version 16.0.2.

@gerbermichi does it fail in compile time? My experience is that it compilation failed in v16.0.1 but passed successfully in v16.0.2.

**Comment by gerbermichi** [comment]
It doesn't compile.

https://github.com/primefaces/primeng/blob/master/src/app/components/api/treenode.ts
```typescript
export interface TreeNode<T = any> {
    /**
     * Label of the node.
     */
    label?: string;
    /**
     * Data represented by the node.
     */
    data?: any;
``` 


`data` should be `T` not `any`.

**Comment by bhalperin** [comment]
> It doesn't compile.
> 
> https://github.com/primefaces/primeng/blob/master/src/app/components/api/treenode.ts
> 
> ```ts
> export interface TreeNode<T = any> {
>     /**
>      * Label of the node.
>      */
>     label?: string;
>     /**
>      * Data represented by the node.
>      */
>     data?: any;
> ```
> 
> `data` should be `T` not `any`.

My app compiles and seems to behave as expected. But you are right, should be `data?: T;`

**Comment by tlinford** [comment]
Also can't compile after updating. could this be reopened?

**Comment by bhalperin** [comment]
👍
