### ISSUE TITLE
[v21.0.0-beta.1] Textarea & Signal Forms Incompatability

### ISSUE THREAD

**Issue by rd-wm** [primefaces/primeng#19116]
### Describe the bug

Textarea is incompatable with Angular 21's Signal Forms due to the `this.ngControl.valueChanges` subscription in Textarea's onInit:

```
ERROR TypeError: can't access property "subscribe", this.ngControl.valueChanges is undefined
    onInit primeng-textarea.mjs:175
    ngOnInit primeng-basecomponent.mjs:205
```

### Reason for not contributing a PR

- [x] Lack of time
- [ ] Unsure how to implement the fix/feature
- [ ] Difficulty understanding the codebase
- [ ] Other

### Reproducer

https://stackblitz.com/edit/github-5aqhxhtg?file=src%2Fapp%2Fapp.component.ts

### Environment

N/A

### Angular version

21.0.0

### PrimeNG version

v20

### Node version

22.17.0

### Steps to reproduce the behavior

1. Use Angular 21's new Signal Forms
2. Use PrimeNG's textarea
3. Observe the console error in browser

### Expected behavior

Should be compatible

**Comment by mertsincan** [comment]
After reviewing the Angular issue tracker, it seems that there are still many ongoing changes related to form signals. We may need to wait a bit longer until things become more stable.
https://x.com/cagataycivici/status/1993708826713845943

**Comment by rhegner** [comment]
This is still broken with RC1

**Comment by rhegner** [comment]
Still not working with 21.0.1

**Comment by rhegner** [comment]
Still broken with 21.0.2

**Comment by rd-wm** [comment]
Shame that it is taking so long to review #19177. Quick win to be had.

**Comment by 3Mowafy** [comment]
You can resolve this issue for now by replacing pTextarea with pInputText.

Example:

```
<textarea
  rows="5"
  cols="30"
  pInputText
  [field]="signalFormProperty.fieldName">
</textarea>
```

Make sure you import the required modules and types:

```
import { InputTextModule } from 'primeng/inputtext';
import { Field } from '@angular/forms/signals';
```

This works because pTextarea does not currently support binding with Field from @angular/forms/signals, while pInputText does.

**Comment by vmuresanu** [comment]
@3Mowafy and if you replace pTextArea with pInputText and your text area has for example `[autoResize]="true"`, you will get a compilation error - `Can't bind to 'autoResize' since it isn't a known property of 'textarea'`. Not to mention that rows and cols that you specified in you example also won't apply visually since it's not a textarea, it's a regular input. So, this is not a good solution.

**Comment by 3Mowafy** [comment]
@vmuresanu 

You’re correct that `pInputText` is not a drop-in replacement for `pTextarea`, and it does not support `autoResize`, `rows`, or `cols` since it’s an `input`, not a `textarea`.

However, a few clarifications:

### Resize behavior
The resize handle is provided by the native `textarea` via CSS, not by PrimeNG.  
`autoResize` in `pTextarea` only controls automatic height adjustment based on content; it does **not** enable or disable manual resizing.

If the goal is to disable resizing, this can be done cleanly via CSS (e.g. Tailwind):

```html
<textarea class="resize-none"></textarea>
```

### `rows` and `cols`
`rows` and `cols` work as expected on a `textarea` and define its initial dimensions.  
If they don’t appear visually, it’s typically due to CSS overrides, not because the attributes are unsupported.

**Summary:**
- `autoResize` ≠ resize
- Resize is controlled via CSS
- `rows` and `cols` are native and fully functional on `textarea`
- Clear separation between behavior (PrimeNG) and styling (CSS/Tailwind)

**Comment by rhegner** [comment]
This is still an issue with 21.0.3.

**Comment by rhegner** [comment]
Still not working with 21.0.4

**Comment by dr460nf1r3** [comment]
Are you actually expecting anything to be changed when the issue is not closed? How about not spamming everyone else's inbox with this useless information?

**Comment by luangong** [comment]
For those who are waiting for an official fix, you can apply #19177 by patching the `primeng` package using pnpm. Here are the steps:

1. Run `pnpm patch primeng`
2. Open `node_modules/.pnpm_patches/primeng@21.1.4/fesm2022/primeng-textarea.mjs` with a text editor (replacing `21.1.4` with the actual version number you are using)
3. Add the optional chaining operator (`?.`) to the following line in `onInit()`:

   ```diff
        onInit() {
            if (this.ngControl) {
   -            this.ngControlSubscription = this.ngControl.valueChanges.subscribe(() => {
   +            this.ngControlSubscription = this.ngControl.valueChanges?.subscribe(() => {
                    this.updateState();
                });
            }
   ```
4. Save the modified file and run `pnpm patch-commit node_modules/.pnpm_patches/primeng@21.1.4`
5. Commit changes to `patches/primeng.patch`, `pnpm-lock.yaml`, and `pnpm-workspace.yaml`.

---

Alternatively, if you are also using v21.1.4, you can just copy the following content and paste it into `patches/primeng.patch`:

```patch
diff --git a/fesm2022/primeng-textarea.mjs b/fesm2022/primeng-textarea.mjs
index e4853c00c75d3e64b46001721a1d3a93da907455..861ef2220a83f2e611739c6d85c647507d2f7247 100644
--- a/fesm2022/primeng-textarea.mjs
+++ b/fesm2022/primeng-textarea.mjs
@@ -136,7 +136,7 @@ class Textarea extends BaseModelHolder {
     }
     onInit() {
         if (this.ngControl) {
-            this.ngControlSubscription = this.ngControl.valueChanges.subscribe(() => {
+            this.ngControlSubscription = this.ngControl.valueChanges?.subscribe(() => {
                 this.updateState();
             });
         }
```

and then add the following lines to `pnpm-workspace.yaml`:

```yaml
patchedDependencies:
  primeng: patches/primeng.patch
```
