### ISSUE TITLE
error on enableIvy false & fullTemplateTypeCheck true

### ISSUE THREAD

**Issue by pulkitnandan** [primefaces/primeng#8887]
**I'm submitting a
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
https://stackblitz.com/edit/github-xamncx is the attempt to reproduce it, but the strange part it's not reproducible on stackblitz while if you download source and run locally with lts node 12, issue is reproducible.

When using  "fullTemplateTypeCheck": true & enableIvy: false set in project's tsconfg.json, I get following errors

`ERROR in node_modules/primeng/dropdown/primeng-dropdown.d.ts.Dropdown.html(17,83): Expected 0 arguments, but got 1.
node_modules/primeng/table/primeng-table.d.ts.ScrollableView.html(18,63): This condition will always return 'true' since the types 'boolean' and 'string' have no overlap.
node_modules/primeng/table/primeng-table.d.ts.ScrollableView.html(27,75): This condition will always return 'true' since the types 'boolean' and 'string' have no overlap.
`
It should not give an error for using  "fullTemplateTypeCheck": true in tsconfig.json and enableIvy: false

Angular 9.1.0 and above & prime-ng 9.1.0

As per this https://github.com/primefaces/primeng/issues/6998 seems someone misses something.

Ubuntu 20.04

* **Node (for AoT issues):** `node --version` =   v12.16.3

**Comment by huineng** [comment]
in additional to the above, there are a few others 

```
ERROR in node_modules/primeng/dropdown/primeng-dropdown.d.ts.Dropdown.html(17,83): Expected 0 arguments, but got 1.
node_modules/primeng/table/primeng-table.d.ts.ScrollableView.html(18,63): This condition will always return 'true' since the types 'boolean' and 'string' have no overlap.
node_modules/primeng/table/primeng-table.d.ts.ScrollableView.html(27,75): This condition will always return 'true' since the types 'boolean' and 'string' have no overlap.
node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(13,67): This condition will always return 'true' since the types 'boolean' and 'string' have no overlap.
node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(14,66): Property 'tableStyle' does not exist on type 'TreeTable'.
node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(14,37): Property 'tableStyleClass' does not exist on type 'TreeTable'.
node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(22,75): This condition will always return 'true' since the types 'boolean' and 'string' have no overlap.
node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(24,66): Property 'tableStyle' does not exist on type 'TreeTable'.
node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(24,37): Property 'tableStyleClass' does not exist on type 'TreeTable'.

**Comment by thimma11** [comment]
I'm getting the same errors since updating primeng from 9.0.5 to 9.1.0. I was not able to find a fix yet, I also opened a thread in Primeng-forum but recieved no helpful answer yet. Hope this will be fixed soon.

**Comment by jurvi** [comment]
Same issues here as well after 9.0.6 -> 9.1.0 upgrade. Having to revert back to 9.0.6 for time being. :(

**Comment by soyiatgit** [comment]
Any update on this or any kind of workaround. I am really stuck at this thing.

**Comment by thimma11** [comment]
I think it will be fixed with the 9.1.1 milestone. My issue on this matter was closed and they added it to the milestone.  Don't know when it will be released though.

**Comment by raul-diego** [comment]
Hi,

As mentioned by [thimma11](https://github.com/primefaces/primeng/issues/8887#issuecomment-641785773)

> I think it will be fixed with the 9.1.1 milestone. My issue on this matter was closed and they added it to the milestone. Don't know when it will be released though.

this seems to be related with issue #8916 which is currently corrected in commit [6267487](https://github.com/primefaces/primeng/commit/62674877070b9d606cd4756f6dbac490d935b98a) and planned for [9.1.1](https://github.com/primefaces/primeng/milestone/151) milestone.

In our side (as spotted by [crumhorn](https://github.com/crumhorn)) we receive similar error trace when compiling solution:

<pre>
node_modules/primeng/dropdown/primeng-dropdown.d.ts.Dropdown.html(17,83): Expected 0 arguments, but got 1.
node_modules/primeng/table/primeng-table.d.ts.ScrollableView.html(18,63): This condition will always return 'true' since the types 'boolean' and 'string' have no overlap.
node_modules/primeng/table/primeng-table.d.ts.ScrollableView.html(27,75): This condition will always return 'true' since the types 'boolean' and 'string' have no overlap.
node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(12,68): Expected 0 arguments, but got 1.
node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(12,106): Expected 0 arguments, but got 1.
node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(12,188): Expected 0 arguments, but got 1.
node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(14,70): Expected 0 arguments, but got 1.
node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(14,110): Expected 0 arguments, but got 1.
node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(14,196): Expected 0 arguments, but got 1.
node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(17,64): Expected 0 arguments, but got 1.
node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(17,102): Expected 0 arguments, but got 1.
node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(17,184): Expected 0 arguments, but got 1.
node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(19,66): Expected 0 arguments, but got 1.
node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(19,106): Expected 0 arguments, but got 1.
node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(19,192): Expected 0 arguments, but got 1.
node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(13,67): This condition will always return 'true' since the types 'boolean' and 'string' have no overlap.
node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(14,66): Property 'tableStyle' does not exist on type 'TreeTable'.
node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(14,37): Property 'tableStyleClass' does not exist on type 'TreeTable'.
node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(22,75): This condition will always return 'true' since the types 'boolean' and 'string' have no overlap.
node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(24,66): Property 'tableStyle' does not exist on type 'TreeTable'.
node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(24,37): Property 'tableStyleClass' does not exist on type 'TreeTable'.
</pre>

As a workaround, we've tweaked _package.json_ file to use specifically version [9.0.6](https://github.com/primefaces/primeng/releases/tag/9.0.6) until release [9.1.1](https://github.com/primefaces/primeng/milestone/151) is ready.

<pre>
{
    ...
    "dependencies": {
        ...
        "primeng": "9.0.6",
        ...
    },
    ...
}
</pre>
Cheers,

**Comment by crumhorn** [comment]
Still happens in 9.1.2 under Angular 8 latest. How is this not top priority when a production build is now not possible while using Primeng? The only "workaround" is to turn off AOT and the build optimizer, which in my opinion is not a workaround at all.

`ERROR in node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(14,144): Expected 1 arguments, but got 0.
node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(17,172): Expected 0 arguments, but got 1.
node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(19,140): Expected 1 arguments, but got 0.
node_modules/primeng/table/primeng-table.d.ts.ScrollableView.html(18,63): This condition will always return 'true' since the types 'boolean' and '"flex"' have no overlap.
node_modules/primeng/table/primeng-table.d.ts.ScrollableView.html(27,75): This condition will always return 'true' since the types 'boolean' and '"flex"' have no overlap.
node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(13,67): This condition will always return 'true' since the types 'boolean' and '"flex"' have no overlap.
node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(14,66): Property 'tableStyle' does not exist on type 'TreeTable'.
node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(14,37): Property 'tableStyleClass' does not exist on type 'TreeTable'.
node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(22,75): This condition will always return 'true' since the types 'boolean' and '"flex"' have no overlap.
node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(24,66): Property 'tableStyle' does not exist on type 'TreeTable'.
node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(24,37): Property 'tableStyleClass' does not exist on type 'TreeTable'.`

**Comment by thimma11** [comment]
Still not working in 9.1.2. As soon as I import and use InputNumberModule I get the below errors:

`ERROR in ./src/app/demo/view/formsdemo.component.ngfactory.js
Module not found: Error: Can't resolve '../../../../node_modules/primeng/inputnumber/primeng-inputnumber.ngfactory' in 'C:\Users\THI\WebstormProjects\verona_test\src\app\demo\view'`

`ERROR in node_modules/primeng/table/primeng-table.d.ts.ScrollableView.html(18,63): This condition will always return 'true' since the types 'boolean' and 'string' have no overlap.
    node_modules/primeng/table/primeng-table.d.ts.ScrollableView.html(27,75): This condition will always return 'true' since the types 'boolean' and 'string' have no overlap.
    node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(13,67): This condition will always return 'true' since the types 'boolean' and 'string' have no overlap.
    node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(14,66): Property 'tableStyle' does not exist on type 'TreeTable'.
    node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(14,37): Property 'tableStyleClass' does not exist on type 'TreeTable'.
    node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(22,75): This condition will always return 'true' since the types 'boolean' and 'string' have no overlap.
    node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(24,66): Property 'tableStyle' does not exist on type 'TreeTable'.
    node_modules/primeng/treetable/primeng-treetable.d.ts.TTScrollableView.html(24,37): Property 'tableStyleClass' does not exist on type 'TreeTable'.
    node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(14,144): Expected 1 arguments, but got 0.
    node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(17,172): Expected 0 arguments, but got 1.
    node_modules/primeng/inputnumber/primeng-inputnumber.d.ts.InputNumber.html(19,140): Expected 1 arguments, but got 0.
`

**Comment by cruzelante098** [comment]
Does #9007 fix this issue? And if so, when will be published to NPM?

**Comment by yigitfindikli** [comment]
Hi,
Fixed in https://github.com/primefaces/primeng/issues/9007 . It's available right now(With PrimeNG v9.1.3). You can check at https://www.npmjs.com/package/primeng .

**Comment by cruzelante098** [comment]
Thank you @yigitfindikli

**Comment by rajeevatprecisely** [comment]
This issue is still coming up in local setup, not on stackBlitz. I have upgraded to PrimeNG v11.4.4 but while building/serving the app I get below error (when ivy is disabled and fullTemplateTypeCheck is true) -

Error: node_modules/primeng/dropdown/primeng-dropdown.d.ts.Dropdown.html(63,43): Property 'emptyFilter' does not exist on type 'Dropdown'.
node_modules/primeng/dropdown/primeng-dropdown.d.ts.Dropdown.html(69,43): Property 'empty' does not exist on type 'Dropdown'.

**Comment by psivadasan-dev** [comment]
The issue is still reproducible with primeng 11.2.3v as well.

**Comment by amitbreuer2** [comment]
I also get the errors @psivadasan-dev mentioned above.
I opened a pr with a fix: https://github.com/primefaces/primeng/pull/10573

**Comment by aksharadeep** [comment]
Hi, Is this issue resolved? 

I am still getting this error with Angular 11 and PrimeNG 11.4.5
node_modules/primeng/multiselect/primeng-multiselect.d.ts.MultiSelect.html(88,47): Property 'empty' does not exist on type 'MultiSelect'.
node_modules/primeng/dropdown/primeng-dropdown.d.ts.Dropdown.html(63,43): Property 'emptyFilter' does not exist on type 'Dropdown'.
node_modules/primeng/dropdown/primeng-dropdown.d.ts.Dropdown.html(69,43): Property 'empty' does not exist on type 'Dropdown'.
node_modules/primeng/listbox/primeng-listbox.d.ts.Listbox.html(48,35): Property 'emptyFilter' does not exist on type 'Listbox'.
node_modules/primeng/listbox/primeng-listbox.d.ts.Listbox.html(54,35): Property 'empty' does not exist on type 'Listbox'.
