### ISSUE TITLE
[vite] Internal server error: fn is not a function

### ISSUE THREAD

**Issue by LMS5413** [primefaces/primeng#17716]
### Describe the bug

I updated angular to v19.1.7 and primeng to 19.0.6 and the bug appear

```

20:32:15 [vite] (ssr) Error when evaluating SSR module /main.server.mjs:
|- TypeError: fn is not a function
    at eval (/mnt/ntfs2/Codes/WebsiteDesafioLunarDev/.angular/cache/19.1.8/WebsiteDesafioLunarDev/vite/deps_ssr/chunk-MRS2SRR7.js:13851:40)
    at Array.forEach (<anonymous>)
    at initFeatures (/mnt/ntfs2/Codes/WebsiteDesafioLunarDev/.angular/cache/19.1.8/WebsiteDesafioLunarDev/vite/deps_ssr/chunk-MRS2SRR7.js:13851:24)
    at Object.eval (/mnt/ntfs2/Codes/WebsiteDesafioLunarDev/.angular/cache/19.1.8/WebsiteDesafioLunarDev/vite/deps_ssr/chunk-MRS2SRR7.js:13810:5)
    at noSideEffects (/mnt/ntfs2/Codes/WebsiteDesafioLunarDev/.angular/cache/19.1.8/WebsiteDesafioLunarDev/vite/deps_ssr/chunk-MRS2SRR7.js:1841:5)
    at ɵɵdefineDirective (/mnt/ntfs2/Codes/WebsiteDesafioLunarDev/.angular/cache/19.1.8/WebsiteDesafioLunarDev/vite/deps_ssr/chunk-MRS2SRR7.js:13808:10)
    at Function.<static_initializer> (/mnt/ntfs2/Codes/WebsiteDesafioLunarDev/.angular/cache/19.1.8/WebsiteDesafioLunarDev/vite/deps_ssr/chunk-JKICIRUQ.js:800:34)
    at eval (/mnt/ntfs2/Codes/WebsiteDesafioLunarDev/.angular/cache/19.1.8/WebsiteDesafioLunarDev/vite/deps_ssr/chunk-JKICIRUQ.js:749:42)
    at async ESModulesEvaluator.runInlinedModule (file:///mnt/ntfs2/Codes/WebsiteDesafioLunarDev/node_modules/vite/dist/node/module-runner.js:1049:5)
    at async SSRCompatModuleRunner.directRequest (file:///mnt/ntfs2/Codes/WebsiteDesafioLunarDev/node_modules/vite/dist/node/module-runner.js:1271:61)

20:32:15 [vite] Internal server error: fn is not a function
      at eval (/mnt/ntfs2/Codes/WebsiteDesafioLunarDev/.angular/cache/19.1.8/WebsiteDesafioLunarDev/vite/deps_ssr/chunk-MRS2SRR7.js:13851:40)
      at Array.forEach (<anonymous>)
      at initFeatures (/mnt/ntfs2/Codes/WebsiteDesafioLunarDev/.angular/cache/19.1.8/WebsiteDesafioLunarDev/vite/deps_ssr/chunk-MRS2SRR7.js:13851:24)
      at Object.eval (/mnt/ntfs2/Codes/WebsiteDesafioLunarDev/.angular/cache/19.1.8/WebsiteDesafioLunarDev/vite/deps_ssr/chunk-MRS2SRR7.js:13810:5)
      at noSideEffects (/mnt/ntfs2/Codes/WebsiteDesafioLunarDev/.angular/cache/19.1.8/WebsiteDesafioLunarDev/vite/deps_ssr/chunk-MRS2SRR7.js:1841:5)
      at ɵɵdefineDirective (/mnt/ntfs2/Codes/WebsiteDesafioLunarDev/.angular/cache/19.1.8/WebsiteDesafioLunarDev/vite/deps_ssr/chunk-MRS2SRR7.js:13808:10)
      at Function.<static_initializer> (/mnt/ntfs2/Codes/WebsiteDesafioLunarDev/.angular/cache/19.1.8/WebsiteDesafioLunarDev/vite/deps_ssr/chunk-JKICIRUQ.js:800:34)
      at eval (/mnt/ntfs2/Codes/WebsiteDesafioLunarDev/.angular/cache/19.1.8/WebsiteDesafioLunarDev/vite/deps_ssr/chunk-JKICIRUQ.js:749:42)
      at async ESModulesEvaluator.runInlinedModule (file:///mnt/ntfs2/Codes/WebsiteDesafioLunarDev/node_modules/vite/dist/node/module-runner.js:1049:5)
      at async SSRCompatModuleRunner.directRequest (file:///mnt/ntfs2/Codes/WebsiteDesafioLunarDev/node_modules/vite/dist/node/module-runner.js:1271:61)
```

### Reason for not contributing a PR

- [ ] Lack of time
- [x] Unsure how to implement the fix/feature
- [ ] Difficulty understanding the codebase
- [x] Other

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-i4pw1kbs?file=package.json

### Environment

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 19.1.8
Node: 22.14.0
Package Manager: bun 1.2.2
OS: linux x64

Angular: 19.1.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1901.8
@angular-devkit/build-angular   19.1.8
@angular-devkit/core            19.1.8
@angular-devkit/schematics      19.1.8
@angular/cli                    19.1.8
@angular/ssr                    19.1.8
@schematics/angular             19.1.8
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0

```

### Angular version

19.1.7

### PrimeNG version

v19

### Node version

v22.14.0 

### Browser(s)

Brave

### Steps to reproduce the behavior

1 - Install latest primeng
2 - Install latest angular 
3 - Use SSR with vite

### Expected behavior

Not show the error

**Comment by awatansa** [comment]
Similar Problem occurred to me as well after bootstrapping new angular application and only importing `ButtonModule`. Tested other few components as well some seems to work, others don't.

- "@angular/core": "^19.1.0",
- "primeng": "^19.0.6",

```js
import { Component, signal } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { ButtonModule } from 'primeng/button';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet, ButtonModule],
  template: `
    <p-button (click)="updateCounter()">{{ counter() }}</p-button>
  `,
})
export class AppComponent {
  counter = signal(0);

  public updateCounter() {
    this.counter.set(this.counter() + 1);
  }
}
```

![Image](https://github.com/user-attachments/assets/039afa6e-53a2-43d5-84e0-1e65a89c86fd)

```
Uncaught TypeError: fn is not a function
    at core.mjs:19348:38
    at Array.forEach (<anonymous>)
    at initFeatures (core.mjs:19348:24)
    at Object.toString (core.mjs:19291:5)
    at noSideEffects (core.mjs:122:5)
    at ɵɵdefineDirective (core.mjs:19289:10)
    at <static_initializer> (primeng-autofocus.mjs:63:33)
    at primeng-autofocus.mjs:11:25
```

**Comment by fgbustoa** [comment]
Same problem. Just updated Angular from 19.1.6 to 19.1.7 (Primeng was already to 19.0.6

**Comment by fgbustoa** [comment]
> Same problem. Downgraded Angular to ~19.0.7 and it works.

Sorry for my noob question ..... how to correctly downgrade angular ???

**Comment by PalSzoboszlay** [comment]
It works with Angular 19.1.6 actually, no need to downgrade a minor version

**Comment by Martinspire** [comment]
I'm running into the same issue with the latest Angular version

```
    "@angular-devkit/build-angular": "^19.1.8",
    "@angular/animations": "^19.1.7",
    "@angular/cdk": "^19.1.5",
    "@angular/cli": "^19.1.8",
    "@angular/common": "^19.1.7",
    "@angular/compiler": "^19.1.7",
    "@angular/compiler-cli": "^19.1.7",
    "@angular/core": "^19.1.7",
    "@angular/forms": "^19.1.7",
    "@angular/platform-browser": "^19.1.7",
    "@angular/platform-browser-dynamic": "^19.1.7",
    "@angular/router": "^19.1.7",
```

**Comment by floreauwe** [comment]
Hi! 
I am not using vite but I have the same issue.
Current version for angular was 19.1.4, also tried to downgrade to 19.0.7 but no change.

Any ideas?
Thanks

**Comment by PlastMan420** [comment]
Same problem here. replicated in a new blank app (angular 19.1) with only primeng 19.0.6

**Comment by nZeus** [comment]
Rennovatebot upgraded angular from `19.1.6` to `19.1.7` this morning, and we now experience the same issue

**Comment by flight2k** [comment]
Same issue since updating Angular to 19.1.6. The project compiles without any problem, but the page never loads due to the error. The project is therefore unusable.

**Comment by ruslan-khomiak** [comment]
I have the same after updating Angular to 19.1.8

**Comment by rpastro** [comment]
According to Angular team the issue is with PrimeNG, which is publishing precompiled code instead of partially compiled code.

See https://github.com/angular/angular/issues/60033

**Comment by thetric** [comment]
So in theory it should be as simple as adding `"compilationMode": "partial"` to https://github.com/primefaces/primeng/blob/master/packages/primeng/tsconfig.json?

**Comment by Martinspire** [comment]
Seems the PR isn't entirely done yet, but would be nice if it can be released quickly

**Comment by slain-m31** [comment]
Hi, I ran into the same problem starting a new app today, but luckily I had recently created another one that worked.
If you can't wait for the patch and need the exact versions that work here they are:

├── @angular-devkit/build-angular@19.1.6
├── @angular/animations@19.1.5
├── @angular/cli@19.1.6
├── @angular/common@19.1.5
├── @angular/compiler-cli@19.1.5
├── @angular/compiler@19.1.5
├── @angular/core@19.1.5
├── @angular/forms@19.1.5
├── @angular/platform-browser-dynamic@19.1.5
├── @angular/platform-browser@19.1.5
├── @angular/router@19.1.5
├── @primeng/themes@19.0.6

**Comment by e-oz** [comment]
Downgrading to:
```json
"@angular/common": "19.2.0-next.3",
"@angular/core": "19.2.0-next.3",
```
(without `^` or `~`) temporarily solves the issue, at least we can continue working on the project.

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primeng/issues/17730

**Comment by thetric** [comment]
You cannot install a version which is not published yet. Wait faster 😀

**Comment by siva-geddada** [comment]
Yeah i have seen in npm library but team is saying that PR Merged right. Just confused Thanks.

![Image](https://github.com/user-attachments/assets/db8265e2-b828-44e2-bf0a-fc621b37c334)

**Comment by siva-geddada** [comment]
Thank you  @mertsincan

**Comment by AdityaPawar2** [comment]
TypeError: fn is not a function
    at node_modules_angular_core_fesm2022_core_mjs-_10e20.js:21013:38
    at Array.forEach (<anonymous>)
    at initFeatures (node_modules_angular_core_fesm2022_core_mjs-_10e20.js:21013:24)
    at Object.toString (node_modules_angular_core_fesm2022_core_mjs-_10e20.js:20801:5)
    at noSideEffects (node_modules_angular_core_fesm2022_core_mjs-_10e20.js:1705:5)
    at Module.ɵɵdefineComponent (node_modules_angular_core_fesm2022_core_mjs-_10e20.js:20766:10)
    at scrolling.mjs:193:96
    at <static_initializer> (scrolling.mjs:1051:712)
    at 79975 (scrolling.mjs:666:40)
    at __webpack_require__ (remoteEntry.js:3416:41) is this same or a different issue ?

**Comment by thetric** [comment]
Hard to tell without a minimal working example. I guess you are better off creating a new issue than commenting on an already closed one
