### ISSUE TITLE
DataTable selected row not draw as selected when initial draw

### ISSUE THREAD

**Issue by lukgit17** [primefaces/primeng#3505]
When is first drawed datatable not draw selected row. Row is drawed as select just if datakey is set like [dataKey]="field". But if is write like [dataKey] then ng build --prod --aot not recognising field.

    Angular version: 4.3.1.
    Angular cli : 1.3.0-rc.1

    PrimeNG version: 4.1.1

**Comment by mattscu** [comment]
Same issue here with primeng 4.1.2, seems to be a new issue as it is working with 4.0.3 (which has other problems like performance)

**Comment by cagataycivici** [comment]
Should be dataKey="field" or [dataKey]="'field'"

**Comment by matthiasscudlik** [comment]
@cagataycivici: I don't know why this is closed?

As a workaround I discovered that you need to use an array for the selectedItem instead of a single reference, even when using selectionMode single

**Comment by lukgit17** [comment]
When run with ng serve working ok with [dataKey]="field" , but when build with -prod -aot ng return error
ERROR in ng:///E:/Development/web/sycproex/frontend/analytics/src/app/randamente/rapoarte/raport-cantitativ/detalii-transate/detalii-transate.component.
html (13,98): Property 'idNod' does not exist on type 'DetaliiTransateComponent'
